"""rename department

Revision ID: 6ee9b7f0414f
Revises: 7a0d951f9119
Create Date: 2024-10-01 20:13:02.869625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee9b7f0414f'
down_revision = '7a0d951f9119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
