"""rename address

Revision ID: 84e45fa2e3fe
Revises: 6ee9b7f0414f
Create Date: 2024-10-01 20:16:15.062230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e45fa2e3fe'
down_revision = '6ee9b7f0414f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
